# This is a basic workflow to help you get started with Actions

name: Build & Deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Switch to Branch
        run: git checkout develop
        
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Install Depencies
        run: yarn install

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
