# This is a basic workflow to help you get started with Actions

name: Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Switch to Branch
        run: git checkout develop
        
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Install Dependencies
        run: yarn install
        
      - name: Build Client & Server
        run: yarn workspace @85830/server build && yarn workspace @85830/client build
        
      - name: Test Server
        run: yarn workspace @85830/server test
